In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors  import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import scale

In [25]:
data=pd.read_csv(r'C:\Users\Ramesh\Downloads\scorecard2019.csv')
data.head()

       Batsmen  Runs  Balls  Fours  sixes
0    DA Warner   692    481    688     51
1  Q de Kock †   529    398    625     41
2     S Dhawan   521    384    598     61
3   AD Russell   510    249    369     33
4    RR Pant †   488    300    523     37

In [36]:
data.isnull().sum()

Batsmen    0
Runs       0
Balls      0
Fours      0
sixes      0
dtype: int64

In [37]:
x=data.iloc[:,2:5]
x.head()

   Balls  Fours  sixes
0    481    688     51
1    398    625     41
2    384    598     61
3    249    369     33
4    300    523     37

In [38]:

y=data.iloc[:,1]
y.head()

0    692
1    529
2    521
3    510
4    488
Name: Runs, dtype: int64

In [39]:
x=scale(x)
x

array([[ 3.59455033e+00,  3.35375006e+00,  2.99636219e+00],
       [ 2.83447852e+00,  2.97163741e+00,  2.26542786e+00],
       [ 2.70627363e+00,  2.80787484e+00,  3.72729652e+00],
       [ 1.47001224e+00,  1.41892566e+00,  1.68068040e+00],
       [ 1.93704432e+00,  2.35297882e+00,  1.97305413e+00],
       [ 2.72458861e+00,  2.89278876e+00,  2.19233443e+00],
       [ 2.08356419e+00,  2.11643289e+00,  2.19233443e+00],
       [ 1.78136696e+00,  1.57662295e+00,  2.63089503e+00],
       [ 1.81799693e+00,  1.65547159e+00,  1.68068040e+00],
       [ 2.15682412e+00,  2.14069401e+00,  2.33852130e+00],
       [ 2.01946175e+00,  1.83743000e+00,  8.76652644e-01],
       [ 1.68063455e+00,  1.84956056e+00,  1.97305413e+00],
       [ 1.84546940e+00,  1.79497304e+00,  2.19233443e+00],
       [ 2.07440670e+00,  1.90414808e+00,  2.41161473e+00],
       [ 1.11287006e+00,  1.23696725e+00,  1.38830667e+00],
       [ 2.04693422e+00,  1.59481879e+00,  2.04614757e+00],
       [ 2.12935165e+00,  2.25593434e+00,  1.75377384e+00],
       [ 1.90957184e+00,  1.56449239e+00,  1.97305413e+00],
       [ 1.60737462e+00,  1.83743000e+00,  2.48470816e+00],
       [ 1.34180735e+00,  7.57810112e-01,  1.24211981e+00],
       [ 1.32349237e+00,  1.34614230e+00,  2.41161473e+00],
       [ 1.59821712e+00,  1.71612439e+00,  1.68068040e+00],
       [ 1.33264986e+00,  1.19451029e+00,  8.03559211e-01],
       [ 1.44253976e+00,  1.66760215e+00,  1.09593294e+00],
       [ 1.36927983e+00,  1.64940631e+00,  9.49746077e-01],
       [ 1.43338227e+00,  8.42724036e-01,  8.76652644e-01],
       [ 1.93704432e+00,  2.22560794e+00,  6.57372346e-01],
       [ 9.48035207e-01,  1.26729365e+00,  1.02283951e+00],
       [ 7.74042863e-01,  1.22483669e+00,  8.76652644e-01],
       [ 9.57192699e-01,  9.09442119e-01,  7.26248850e-02],
       [ 4.07743192e-01,  1.69477927e-01,  5.11185481e-01],
       [ 6.91625437e-01,  6.48635068e-01,  5.11185481e-01],
       [ 6.18365503e-01,  6.85026749e-01,  2.91905183e-01],
       [ 6.09208011e-01,  7.21418431e-01,  9.49746077e-01],
       [ 5.17633093e-01,  4.06023857e-01,  1.31521324e+00],
       [ 5.35948077e-01,  6.48635068e-01, -4.68547645e-04],
       [ 4.16900684e-01,  6.66830908e-01,  4.38092048e-01],
       [ 3.80270717e-01,  3.69632176e-01,  8.76652644e-01],
       [ 7.74042863e-01,  5.45525303e-01,  1.45718318e-01],
       [ 6.00050520e-01,  2.36196010e-01,  2.91905183e-01],
       [ 5.63420552e-01,  5.45525303e-01,  2.91905183e-01],
       [ 4.99318110e-01,  4.78807220e-01,  5.11185481e-01],
       [ 2.88695799e-01,  5.39460023e-01, -2.19748846e-01],
       [ 7.37412896e-01,  5.75851705e-01,  4.38092048e-01],
       [ 3.43640749e-01,  4.18154418e-01,  5.11185481e-01],
       [ 3.80270717e-01,  4.84872501e-01,  1.45718318e-01],
       [ 7.80734877e-02, -4.28068818e-02, -2.19748846e-01],
       [ 6.89159959e-02,  6.03028826e-02,  7.26248850e-02],
       [-2.26589220e-02,  5.71536024e-03,  6.57372346e-01],
       [ 2.70380815e-01,  1.45216806e-01, -7.35619803e-02],
       [ 1.23860947e-01,  2.36196010e-01,  4.38092048e-01],
       [ 9.63884712e-02,  5.71536024e-03, -4.68547645e-04],
       [-1.14233840e-01, -3.49920015e-04, -1.46655413e-01],
       [-2.60753708e-01, -3.21809774e-01, -7.35619803e-02],
       [-4.34393841e-03,  1.17806405e-02, -7.35619803e-02],
       [-4.34393841e-03, -1.09524965e-01, -1.46655413e-01],
       [ 1.05545963e-01,  1.69477927e-01, -1.46655413e-01],
       [-1.23391332e-01, -5.03768182e-01, -1.46655413e-01],
       [-1.69178791e-01, -1.15590245e-01,  7.26248850e-02],
       [-3.06541167e-01, -3.21809774e-01,  2.18811750e-01],
       [-1.41706315e-01, -2.06569449e-01, -4.39029143e-01],
       [-3.24856151e-01, -1.94438888e-01,  2.18811750e-01],
       [-1.69178791e-01, -3.15744493e-01, -7.35619803e-02],
       [-5.26320970e-01, -3.27875054e-01, -5.12122576e-01],
       [-3.24856151e-01, -2.00504169e-01, -4.39029143e-01],
       [-2.05808758e-01, -3.40005615e-01, -3.65935711e-01],
       [-3.15698659e-01, -2.49026411e-01, -5.85216009e-01],
       [-3.70643610e-01, -3.09679213e-01, -2.92842278e-01],
       [-4.43903544e-01, -4.97702901e-01, -3.65935711e-01],
       [-4.43903544e-01, -4.97702901e-01, -3.65935711e-01],
       [-2.51596217e-01, -2.00504169e-01, -2.92842278e-01],
       [-2.33281233e-01, -3.46070895e-01, -3.65935711e-01],
       [-3.88958593e-01, -3.52136175e-01, -1.46655413e-01],
       [-2.88226184e-01, -3.03613933e-01, -3.65935711e-01],
       [-3.34013643e-01, -3.27875054e-01, -4.39029143e-01],
       [-3.61486118e-01, -3.70332016e-01, -5.12122576e-01],
       [-5.53793446e-01, -4.91637621e-01, -5.12122576e-01],
       [-4.71376020e-01, -3.64266736e-01, -4.39029143e-01],
       [-3.98116085e-01, -3.64266736e-01, -6.58309441e-01],
       [-5.08005987e-01, -6.19008506e-01, -5.85216009e-01],
       [-4.98848495e-01, -4.00658417e-01, -6.58309441e-01],
       [-5.99580905e-01, -4.91637621e-01, -5.85216009e-01],
       [-4.71376020e-01, -4.43115379e-01, -6.58309441e-01],
       [-5.99580905e-01, -5.70486264e-01, -7.31402874e-01],
       [-6.08738396e-01, -6.85726589e-01, -5.12122576e-01],
       [-5.81265921e-01, -6.19008506e-01, -5.12122576e-01],
       [-7.18628298e-01, -7.46379392e-01, -5.85216009e-01],
       [-5.90423413e-01, -4.79507060e-01, -5.85216009e-01],
       [-7.00313314e-01, -6.85726589e-01, -5.85216009e-01],
       [-5.90423413e-01, -6.06877946e-01, -5.85216009e-01],
       [-6.36210872e-01, -6.43269627e-01, -5.85216009e-01],
       [-6.54525855e-01, -6.49334908e-01, -6.58309441e-01],
       [-5.90423413e-01, -5.40159863e-01, -6.58309441e-01],
       [-6.54525855e-01, -6.25073787e-01, -6.58309441e-01],
       [-6.91155822e-01, -7.03922430e-01, -6.58309441e-01],
       [-6.54525855e-01, -6.31139067e-01, -5.85216009e-01],
       [-6.91155822e-01, -5.76551545e-01, -5.85216009e-01],
       [-7.46100773e-01, -7.16052991e-01, -6.58309441e-01],
       [-6.72840839e-01, -6.61465468e-01, -7.31402874e-01],
       [-7.09470806e-01, -7.22118271e-01, -5.85216009e-01],
       [-7.36943281e-01, -7.52444672e-01, -6.58309441e-01],
       [-7.18628298e-01, -6.55400188e-01, -6.58309441e-01],
       [-6.63683347e-01, -7.03922430e-01, -7.31402874e-01],
       [-6.91155822e-01, -6.25073787e-01, -6.58309441e-01],
       [-7.82730740e-01, -7.88836354e-01, -6.58309441e-01],
       [-7.27785790e-01, -6.85726589e-01, -6.58309441e-01],
       [-7.18628298e-01, -7.03922430e-01, -7.31402874e-01],
       [-7.27785790e-01, -7.40314112e-01, -7.31402874e-01],
       [-7.82730740e-01, -8.07032194e-01, -7.31402874e-01],
       [-7.18628298e-01, -6.97857150e-01, -7.31402874e-01],
       [-7.00313314e-01, -6.61465468e-01, -6.58309441e-01],
       [-7.82730740e-01, -7.70640513e-01, -5.85216009e-01],
       [-6.63683347e-01, -7.22118271e-01, -6.58309441e-01],
       [-7.00313314e-01, -7.09987710e-01, -7.31402874e-01],
       [-7.73573248e-01, -7.40314112e-01, -7.31402874e-01],
       [-7.27785790e-01, -7.40314112e-01, -6.58309441e-01],
       [-7.82730740e-01, -7.64575233e-01, -6.58309441e-01],
       [-7.09470806e-01, -6.79661309e-01, -7.31402874e-01],
       [-6.72840839e-01, -7.03922430e-01, -7.31402874e-01],
       [-7.64415757e-01, -8.07032194e-01, -7.31402874e-01],
       [-6.63683347e-01, -7.58509952e-01, -7.31402874e-01],
       [-7.55258265e-01, -7.64575233e-01, -7.31402874e-01],
       [-7.73573248e-01, -8.19162755e-01, -7.31402874e-01],
       [-7.82730740e-01, -8.07032194e-01, -6.58309441e-01],
       [-7.36943281e-01, -7.34248831e-01, -7.31402874e-01],
       [-6.81998331e-01, -6.85726589e-01, -7.31402874e-01],
       [-7.36943281e-01, -7.09987710e-01, -7.31402874e-01],
       [-7.82730740e-01, -7.82771073e-01, -6.58309441e-01],
       [-7.46100773e-01, -7.52444672e-01, -7.31402874e-01],
       [-7.18628298e-01, -6.85726589e-01, -7.31402874e-01],
       [-7.46100773e-01, -7.09987710e-01, -7.31402874e-01],
       [-7.64415757e-01, -7.40314112e-01, -7.31402874e-01],
       [-7.82730740e-01, -7.70640513e-01, -7.31402874e-01],
       [-7.55258265e-01, -7.70640513e-01, -7.31402874e-01],
       [-7.73573248e-01, -8.13097475e-01, -7.31402874e-01],
       [-7.82730740e-01, -7.88836354e-01, -7.31402874e-01],
       [-7.82730740e-01, -7.64575233e-01, -7.31402874e-01],
       [-7.91888232e-01, -7.94901634e-01, -7.31402874e-01],
       [-7.82730740e-01, -7.64575233e-01, -7.31402874e-01],
       [-8.01045724e-01, -8.13097475e-01, -7.31402874e-01],
       [-7.64415757e-01, -6.85726589e-01, -7.31402874e-01],
       [-7.91888232e-01, -8.00966914e-01, -7.31402874e-01],
       [-7.73573248e-01, -7.70640513e-01, -7.31402874e-01],
       [-7.91888232e-01, -7.58509952e-01, -7.31402874e-01],
       [-7.73573248e-01, -7.76705793e-01, -7.31402874e-01],
       [-7.91888232e-01, -8.00966914e-01, -7.31402874e-01],
       [-7.82730740e-01, -7.76705793e-01, -7.31402874e-01],
       [-8.01045724e-01, -7.58509952e-01, -7.31402874e-01],
       [-8.01045724e-01, -8.00966914e-01, -7.31402874e-01],
       [-8.10203216e-01, -8.13097475e-01, -7.31402874e-01],
       [-8.01045724e-01, -8.13097475e-01, -7.31402874e-01],
       [-8.10203216e-01, -8.07032194e-01, -7.31402874e-01],
       [-8.01045724e-01, -7.76705793e-01, -7.31402874e-01],
       [-8.01045724e-01, -8.13097475e-01, -7.31402874e-01],
       [-7.91888232e-01, -7.88836354e-01, -7.31402874e-01],
       [-8.01045724e-01, -8.13097475e-01, -7.31402874e-01]])

In [40]:


x=pd.DataFrame(x)
x.head()

          0         1         2
0  3.594550  3.353750  2.996362
1  2.834479  2.971637  2.265428
2  2.706274  2.807875  3.727297
3  1.470012  1.418926  1.680680
4  1.937044  2.352979  1.973054

In [41]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [42]:
y_test.head()

26     282
54     110
37     190
112      7
24     296
Name: Runs, dtype: int64

In [43]:
knn_model=KNeighborsClassifier(n_neighbors=10, metric='euclidean')
knn_model.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [44]:
knn_model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [45]:
y_predict = knn_model.predict(x_test)
np.mean(y_predict == y_test)
#y_predict

0.125

In [48]:
confusion_matrix(y_predict,y_test)

array([[3, 2, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
accuracy_score(y_predict,y_test)

0.125